project: adamfjeldsted/sandbox
open-webbrowser: false
name: Examples
tags: [imgaug, vgg16_unet, freeze_schedule]

parameters:
  # Input pipe parameters (Normalization is based in the parameter network_type)
  aug_crop_flip: true
  aug_affine: true
  aug_intensity_seq: true
  aug_mask_smooth: false
  aug_channel_augmenter: false

  # Dataset parameters
  path: '/hdd/datasets/TGS'
  img_type: 'images' # 'images' and 'images_textured' (3 channels)
  resize: 128
  prefetch_batches: 5
  batch_size: 32
  num_parallel_calls: 4
  remove_bad_id: true

  # Learning rate settings
  lr_type: 'reduce_on_plateau'  # 'basic', 'reduce_on_plateau'
  learning_rate: 0.0001
  lr_patience: 10
  lr_plateau_reduce: 0.9
  lr_plateau_min_lr: 0.000005

  # Layer freeze settings (none is no freeze)
  layer_freeze_type: 'on_epoch' # 'none', 'on_epoch'
  freeze_until_epoch: 50

  # Early stopping parameters
  early_paticence: 50
  early_start_epoch: 2

  # Loss settings
  cross_entr_weight: 1.0
  reg_weight: 0.0001
  dice_weight: 1.0

  # Experiment parameters
  resume_training_from:
  output_dir: '/hdd/datasets/TGS/trained_models/network_types'
  export_from:
  train_epochs: 200
  start_eval_at_epoch: 5
  eval_per_n_epoch: 1
  eval_steps: 20
  keep_checkpoint_max: 10
  save_summary_steps: 180
  save_checkpoints_steps: 1000

  # Optimizer
  optimizer: 'adam'
  adam_b1: 0.9
  adam_b2: 0.99
  rms_decay: 0.9
  rms_momentum: 0.0

  # Network selector
  network_type: 'vgg_16_unet'
  warm_start: true

  ### Network architectures ###

  # Common variables
  start_filters: 64
  dropout: 0.5
  batchnorm: true
  nbr_of_classes: 1

  #### resnet_152 ####
  resnet_chkp: '/hdd/pretrained_networks/resnet_152/resnet_v2_152.ckpt'
  resnet_freeze: true
  resnet_upsampling_type: 'subpixel'

  #### nasnet ####
  nasnet_chkp: '/hdd/pretrained_networks/nasnet/model.ckpt'
  nasnet_freeze: true

  #### vgg_16_unet ####
  vgg16_chkp: '/hdd/pretrained_networks/vgg16/vgg_16.ckpt'
  vgg_16_freeze: false
  vgg_16_stack_depth: 5
  vgg_16_unet_upsampling_type: 'spatial_unpool' # subpixel, bilinear, artifact_upsampling, spatial_unpool


  #### unet ####
  unet_depth: 5
  unet_residual: false
  unet_start_filters: 32
  unet_upsampling_type: 'upsample2D'  # upsample2D, subpixel, bilinear, artifact_upsampling, conv_transpose

  ### NON_CHANGABLE_CONSTANTS ###
  original_size: 101
  dataset_size: 4000
  validation_split: 0.1
  salt_vs_not_ratio: 0.247965861 # 0.247965861

metric:
  channel: 'iou_coe_50'
  goal: maximize

exclude:
  - output
  - cache
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - Dockerfiles/base.Dockerfile
  - token